[project]
name = "toygres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prompt-toolkit>=3.0.52",
    "psycopg2-binary>=2.9.11",
    "questionary>=2.1.1",
    "rich>=14.3.3",
]
